#!/usr/bin/env python3
"""Fake herdr CLI: logs argv and answers the few calls cloudsheep makes."""
import json
import os
import sys

with open(os.environ['FAKE_HERDR_LOG'], 'a') as log:
    log.write(json.dumps(sys.argv[1:]) + '\n')
args = sys.argv[1:]
if args[:2] == ['tab', 'create']:
    print(json.dumps({'id': '1', 'result': {'type': 'tab_created', 'tab': {'tab_id': 't1'}, 'root_pane': {'pane_id': 'w:p9'}}}))
elif args[:2] == ['pane', 'split']:
    print(json.dumps({'id': '1', 'result': {'type': 'pane_info', 'pane': {'pane_id': 'w:p7'}}}))
else:
    print(json.dumps({'id': '1', 'result': {'type': 'ok'}}))
