#!/usr/bin/env python3
"""Fake ssh: runs the remote command locally with HOME=$FAKE_REMOTE_HOME and logs argv."""
import os
import sys

args = sys.argv[1:]
with open(os.environ['FAKE_SSH_LOG'], 'a') as log:
    log.write(repr(args) + '\n')
takes_value = {'-p', '-i', '-J', '-o', '-L', '-l', '-F'}
i = 0
while i < len(args) and args[i].startswith('-'):
    i += 2 if args[i] in takes_value else 1
host, command = args[i], ' '.join(args[i + 1:])
if os.environ.get('FAKE_SSH_FAIL'):
    sys.stderr.write('ssh: connect to host ' + host + ': Connection refused\n')
    sys.exit(255)
env = {**os.environ, 'HOME': os.environ['FAKE_REMOTE_HOME']}
os.chdir(env['HOME'])
os.execve('/bin/sh', ['sh', '-c', command or 'true'], env)
